images:
- gcr.io/$PROJECT_ID/container-builder-test:v0.0.1

steps:
- name: gcr.io/cloud-builders/yarn
  args: ['install']

- name: gcr.io/cloud-builders/yarn
  args: ['build']

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/container-builder-test:v0.0.1', '.']
