# User-defined substitutions:
#   _CLOUDSDK_COMPUTE_ZONE
#   _CLOUDSDK_CONTAINER_CLUSTER

images:
- gcr.io/$PROJECT_ID/container-builder-test:v0.0.1

steps:
- name: gcr.io/cloud-builders/yarn
  args: ['install']

- name: gcr.io/cloud-builders/yarn
  args: ['build']

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/container-builder-test:v0.0.1', '.']

- name: gcr.io/cloud-builders/gcloud
  env:
  - CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}
  - CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}
  - KUBECONFIG=/kube/config
  volumes:
  - name: kube
    path: /kube
  entrypoint: 'sh'
  args:
  - -c
  - |
    CLUSTER=$$(gcloud config get-value container/cluster)
    PROJECT=$$(gcloud config get-value core/project)
    ZONE=$$(gcloud config get-value compute/zone)

    gcloud container clusters get-credentials "$${CLUSTER}" \
      --project "$${PROJECT}" \
      --zone "$${ZONE}"

- name: gcr.io/cloud-builders/gcloud
  env:
  - KUBECONFIG=/kube/config
  volumes:
  - name: kube
    path: /kube
  entrypoint: 'sh'
  args:
  - -c
  - |
    kubectl apply -f .k8s
